apiVersion: v2
appVersion: 1.0.0
description: Codefresh gitops runtime umbrella chart
name: codefresh-gitops-runtime
version: 0.19.2-github-push-fix
dependencies:
  - name: gitops-runtime
    repository: oci://quay.io/codefresh
    version: 0.19.2-github-push-fix
