gitops-runtime:
  global:
    codefresh:
      accountId: 669ac8d4d746b873ac8410a2
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: iris-personal
